version: '3.9'

services:
    postgres:
        container_name: reservation-postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=reservation
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data 

volumes:
    postgres_data:

networks:
  reservation:
    driver: bridge